IMPORT LIBRARIES

In [ ]:
import pandas as pd
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.default = "plotly_white"
import plotly.express as px

IMPORT & READ DATA

In [ ]:
data=pd.read_csv("/content/Apple-Fitness-Data.csv")
data

,Date,Time,Step Count,Distance,Energy Burned,Flights Climbed,Walking Double Support Percentage,Walking Speed
0,2023-03-21,16:01:23,46,0.02543,14.620,3,0.304,3.060
1,2023-03-21,16:18:37,645,0.40041,14.722,3,0.309,3.852
2,2023-03-21,16:31:38,14,0.00996,14.603,4,0.278,3.996
3,2023-03-21,16:45:37,13,0.00901,14.811,3,0.278,5.040
4,2023-03-21,17:10:30,17,0.00904,15.153,3,0.281,5.184
...,...,...,...,...,...,...,...,...
144,2023-04-01,16:04:23,87,0.05872,13.162,3,0.298,5.364
145,2023-04-01,16:33:18,37,0.02039,4.135,1,0.295,5.400
146,2023-04-01,16:49:49,969,0.65379,31.416,3,0.274,5.292
147,2023-04-01,17:09:06,640,0.42356,13.250,6,0.282,4.860
148,2023-04-01,17:47:07,1081,0.67835,14.131,1,0.265,5.040

CHECKING FOR NULL VALUES

In [ ]:
data.isnull().sum()

Date                                 0
Time                                 0
Step Count                           0
Distance                             0
Energy Burned                        0
Flights Climbed                      0
Walking Double Support Percentage    0
Walking Speed                        0
dtype: int64

The data doesn't have null values

ANALYZING STEP COUNT OVER TIME

In [ ]:
# Step Count Over Time
fig1 = px.line(data, x="Time",
               y="Step Count",
               title="Step Count Over Time")
fig1.show()

ANALYZING DISTANCE COVERED OVER TIME

In [ ]:
# Distance Covered Over Time
fig2 = px.line(data, x="Time",
               y="Distance",
               title="Distance Covered Over Time")
fig2.show()

ANALYZING ENERGY BURNED OVER TIME

In [ ]:
# Energy Burned Over Time
fig3 = px.line(data, x="Time",
               y="Energy Burned",
               title="Energy Burned Over Time")
fig3.show()

ANALYZING WALKING SPEED OVER TIME

In [ ]:
# Walking Speed Over Time
fig4 = px.line(data, x="Time",
               y="Walking Speed",
               title="Walking Speed Over Time")
fig4.show()

CALCULATING AVERAGE STEP COUNT PER DAY

In [ ]:
# Calculate Average Step Count per Day
average_step_count_per_day = data.groupby("Date")["Step Count"].mean().reset_index()
average_step_count_per_day

          Date  Step Count
0   2023-03-21  137.636364
1   2023-03-22  354.233333
2   2023-03-23  109.125000
3   2023-03-24   64.666667
4   2023-03-25  117.000000
5   2023-03-26  101.000000
6   2023-03-27   48.875000
7   2023-03-28  163.750000
8   2023-03-29  169.578947
9   2023-03-30  384.181818
10  2023-03-31  372.166667
11  2023-04-01  306.916667

VISUALIZING CALCULATED AVERAGE STEP COUNT PER DAY

In [ ]:
fig5 = px.bar(average_step_count_per_day, x="Date",
              y="Step Count",
              title="Average Step Count per Day")
fig5.update_xaxes(type='category')
fig5.show()

CALCULATING WALKING EFFICIENCY

In [ ]:
# Calculate Walking Efficiency
data["Walking Efficiency"] = data["Distance"] / data["Step Count"]
data["Walking Efficiency"]

0      0.000553
1      0.000621
2      0.000711
3      0.000693
4      0.000532
         ...
144    0.000675
145    0.000551
146    0.000675
147    0.000662
148    0.000628
Name: Walking Efficiency, Length: 149, dtype: float64

ANALYZING WALKING EFFICIENCY OVER TIME

In [ ]:
fig6 = px.line(data, x="Time",
               y="Walking Efficiency",
               title="Walking Efficiency Over Time")
fig6.show()

ANALYZING STEP COUNT AND WALKING SPPED VARIATIONS BY TIME INTERVALS

CREATE TIME INTERVALS

In [ ]:
# Create Time Intervals
time_intervals = pd.cut(pd.to_datetime(data["Time"]).dt.hour,
                        bins=[0, 12, 18, 24],
                        labels=["Morning", "Afternoon", "Evening"],
                        right=False)
data["Time Interval"] = time_intervals
data["Time Interval"]

<ipython-input-18-26e154cfec9f>:2: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

0      Afternoon
1      Afternoon
2      Afternoon
3      Afternoon
4      Afternoon
         ...
144    Afternoon
145    Afternoon
146    Afternoon
147    Afternoon
148    Afternoon
Name: Time Interval, Length: 149, dtype: category
Categories (3, object): ['Morning' < 'Afternoon' < 'Evening']

ANALYZING STEP COUNT AND WALKING SPEED VARIATIONS BY TIME INTERVALS

In [ ]:
# Variations in Step Count and Walking Speed by Time Interval
fig7 = px.scatter(data, x="Step Count",
                  y="Walking Speed",
                  color="Time Interval",
                  title="Step Count and Walking Speed Variations by Time Interval",
                  trendline='ols')
fig7.show()